apiVersion: v1
kind: Template
labels:
  template: openshift-todo-demo-jenkinsfile
metadata:
  name: openshift-todo-demo-jenkinsfile
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "${PROJECT_NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
    labels:
      application: ${APPLICATION_NAME}-jenkinsfile
    name: ${APPLICATION_NAME}-jenkinsfile
  spec:
    source:
      git:
        ref: ${SOURCE_REF}
        uri: ${SOURCE_URL}
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
      type: Generic
    triggers:
    - github:
        secret: {GIT_HUB_TRIGGER}
      type: GitHub
    - generic:
        secret: {GIT_GENERIC_TRIGGER}
      type: Generic
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: todo-app
- description: The name of Dev project
  name: DEV_PROJECT
  required: true
  value: demo-project
- description: Git source URI for application
  name: SOURCE_URL
  required: true
  value: https://github.com/anteuz/todo-app
- description: Git branch/tag reference
  name: SOURCE_REF
  value: master